const stringSimilarity = require("string-similarity")

console.log(stringSimilarity.compareTwoStrings("Studio Killers - Jenny (I Wanna Ruin Our Friendship) OFFICIAL LYRIC VIDEO", "Studio Killers - Jenny (Lyrics)"))
console.log(stringSimilarity.compareTwoStrings("Studio Killers - Jenny (I Wanna Ruin Our Friendship) OFFICIAL LYRIC VIDEO", "Studio Killers - I wanna ruin our friendship (Jenny) (Lyrics)"))

const str = [
  "Prospa - The Thrill (Official Animated Video)",
  "Beachball - Nalin & Kane (Chris Lake Remix)",
  "The Streets - Dry Your Eyes (Official Video)",
  "070 - Honey ft. Shake, Ralphy River, Hack, Treee Safari (Official Audio)",
  "Evanescence - Bring Me To Life (Official Music Video)",
  "Calvin Harris & Disciples - How Deep Is Your Love",
  "Justin Timberlake - Like I Love You",
  "Jay-Z & Kanye West - Ni**as In Paris (Explicit)",
  "Move Ya Body",
  "Drake - Chicago Freestyle (Carnage & Sonny Fodera Remix)",
  "Life in Technicolor ii Lyrics by Coldplay",
  "MaximilianMus - Oh Yeah Yeah",
  "Cloonee - Separated",
  "Au/Ra - Emoji (Official Video)",
  "Wankelmut & Emma Louise - My Head Is A Jungle (MK Radio Edit)",
  "Edward Maya & Vika Jigulina - Stereo Love (Official Music Video)",
  "Cardi B - WAP feat. Megan Thee Stallion [Official Music Video]",
  "Samim - 'Heater' (Official Video)",
  "Fleetwood Mac - Dreams (Lyrics)",
  "Cranberries Zombie  ( lyrics )",
  "Lil Nas X - HOLIDAY (Lyrics)",
  "ZHU - Faded (Official Music Video)",
  "Nathan Evans - Wellerman (220 KID & Billen Ted Remix) | Official Audio",
  "Lil Nas X - HOLIDAY (Lyrics)",
  "Mike Candys & Neptunica & Marmy - Overdose (Official Video 4K)",
  "Harris & Ford x Mike Candys - My Way (Official Video HD)",
  "VIZE & Leony - Dolly Song (Lyrics) (Devil's Cup)",
  "Calvin Harris - My Way (Official Video)",
  "SAINt JHN - Roses (Imanbek Remix) (Official Music Video)",
  "David Guetta live @ Fun Radio Live Stream Experience",
  "Cannibal Corpse - I Cum Blood [Lyrics On Screen] [1080p]",
  "Your Favourite Garçon - Baby Work It",
  // "Studio Killers - Jenny (I Wanna Ruin Our Friendship) OFFICIAL LYRIC VIDEO",
  "AlunaGeorge - Best Be Believing (Shadow Child Remix)",
  "Test \" Im Popular \" (Official Video)",
  "Jackin House",
  "Mike Candys - Like That",
  "Nathan Evans - Wellerman (220 KID & Billen Ted Remix) | TikTok Remix Official Lyric Video",
  "Lil Nas X - HOLIDAY (Official Video)",
  "Disclosure - Tondo (Visualiser)",
  "Disclosure - Watch Your Step (Lyrics)ft. Kelis",
  "Nyan Cat - 10 HOURS [ BEST SOUND QUALITY ] 4K UHD ULTRA HD",
  "Mike Candys - Push It",
  "Flo Rida - In The Ayer (feat. Will.i.am) [Official Video]",
  "Test x Miss LaFamilia - All Mine [Music Video] | Link Up TV",
  "Riton x Nightcrawlers - Friday (Dopamine Re-Edit) [feat. Mufasa & Hypeman] (It's Friday Then Song)",
  "Disclosure, Kelis - Watch Your Step",
  "Tate McRae - you broke me first (Luca Schreiner Remix) Lyrics",
  "AVAION - Love Again (Lyrics)",
  "I really miss my niggaaaaaa (better version)",
  "D Block Europe - Home Pussy (LYRICS!!!)",
  "The Chicken Wing Beat",
  "STAND HIGH PATROL: The Big Tree",
  "Rising Tide",
  "Wiz Khalifa - Black And Yellow [Official Music Video]",
  "Cardi B - WAP (David Guetta Remix) [feat. Megan Thee Stallion]",
  "Studio Killers - Jenny (Lyrics)",
  "Zedd, Griff - Inside Out (Lyric Video)",
  "MATTN & Klaas - The Logical Song",
  "Imanbek & GOODBOYS - Goodbye (Lyrics)",
  "Bad Bunny & Jhay Cortez - Dákiti (David Guetta Remix)",
  "New Year Music Mix 2021 ♫ Best Music 2020 Party Mix ♫ Remixes of Popular Songs",
  "Studio Killers - I wanna ruin our friendship (Jenny) (Lyrics)",
  "Riton x Nightcrawlers - Friday ft. Mufasa & Hypeman (Dopamine Re-Edit) [Lyric Video]",
  "Shakira - Whenever, Wherever (BIMONTE & CRIZBI cover) [Magic Cover Release (Lyrics) |full song",
  "Tabba x Dj Goja - Secrets (Official Single)",
  "Harddope - Heathens ft. Halvorsen (Lyrics)",
  "Besomorph & Anthony Keyrouz - Apologize (ft. Lunis) [Lyric Video]",
  "Tabba x Dj Goja - Secrets (Magic Free Release)",
  "Shane Codd - Get Out My Head (Official Lyric Video)",
  "Anne-Marie x KSI x Digital Farm Animals - Don’t Play (Lyrics)",
  "Megan Thee Stallion - Savage [Official Audio]",
]

console.log(stringSimilarity.findBestMatch("Studio Killers - Jenny (I Wanna Ruin Our Friendship) OFFICIAL LYRIC VIDEO", str))